# see https://pre-commit.com
# to use, run `python3.10 -m venv venv`; `source venv/bin/activate`; `pip install -r requirements-dev.txt`; `pre-commit install`
# do not automatically re-stage and re-commit the changes: https://stackoverflow.com/a/64309843
repos:
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v2.3.0
    hooks:
      - id: check-yaml
      # - id: end-of-file-fixer
      - id: trailing-whitespace
  - repo: https://github.com/psf/black
    rev: 24.1.1
    hooks:
      - id: black
  - repo: https://github.com/pre-commit/mirrors-prettier
    rev: v3.1.0 # Use the sha / tag you want to point at
    hooks:
      - id: prettier
